export let team2d = {
    "players": {
        "playing XI": [
            {
                "id": 576,
                "name": "Rohit",
                "fullName": "Rohit Sharma",
                "nickName": "Rohit",
                "captain": false,
                "role": "Batsman",
                "keeper": false,
                "substitute": false,
                "teamId": 62,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm off break",
                "teamName": "MI",
                "faceImageId": 616514,
                "inMatchChange": "MOUT"
            },
            {
                "id": 13070,
                "name": "Rickelton",
                "fullName": "Ryan Rickelton",
                "nickName": "Rickelton",
                "captain": false,
                "role": "WK-Batsman",
                "keeper": true,
                "substitute": false,
                "teamId": 62,
                "battingStyle": "LEFT",
                "bowlingStyle": "",
                "teamName": "MI",
                "faceImageId": 619865,
                "isOverseas": true
            },
            {
                "id": 12258,
                "name": "Will Jacks",
                "fullName": "Will Jacks",
                "nickName": "Will Jacks",
                "captain": false,
                "role": "Batting Allrounder",
                "keeper": false,
                "substitute": false,
                "teamId": 62,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm off break",
                "teamName": "MI",
                "faceImageId": 594344,
                "isOverseas": true
            },
            {
                "id": 7915,
                "name": "Suryakumar Yadav",
                "fullName": "Suryakumar Yadav",
                "nickName": "Suryakumar Yadav",
                "captain": true,
                "role": "Batsman",
                "keeper": false,
                "substitute": false,
                "teamId": 62,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm off break",
                "teamName": "MI",
                "faceImageId": 352481
            },
            {
                "id": 14504,
                "name": "Tilak Varma",
                "fullName": "Tilak Varma",
                "nickName": "Tilak Varma",
                "captain": false,
                "role": "Batsman",
                "keeper": false,
                "substitute": false,
                "teamId": 62,
                "battingStyle": "LEFT",
                "bowlingStyle": "Right Arm off break",
                "teamName": "MI",
                "faceImageId": 226525
            },
            {
                "id": 36139,
                "name": "Naman Dhir",
                "fullName": "Naman Dhir",
                "nickName": "Naman Dhir",
                "captain": false,
                "role": "Batsman",
                "keeper": false,
                "substitute": false,
                "teamId": 62,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm off break",
                "teamName": "MI",
                "faceImageId": 182026
            },
            {
                "id": 36454,
                "name": "Robin Minz",
                "fullName": "Robin Minz",
                "nickName": "Robin Minz",
                "captain": false,
                "role": "WK-Batsman",
                "keeper": false,
                "substitute": false,
                "teamId": 62,
                "battingStyle": "LEFT",
                "bowlingStyle": "Right Arm off break",
                "teamName": "MI",
                "faceImageId": 182026
            },
            {
                "id": 10100,
                "name": "Santner",
                "fullName": "Mitchell Santner",
                "nickName": "Santner",
                "captain": false,
                "role": "Bowling Allrounder",
                "keeper": false,
                "substitute": false,
                "teamId": 62,
                "battingStyle": "LEFT",
                "bowlingStyle": "Left arm orthodox",
                "teamName": "MI",
                "faceImageId": 616427,
                "isOverseas": true
            },
            {
                "id": 7836,
                "name": "D Chahar",
                "fullName": "Deepak Chahar",
                "nickName": "Chahar",
                "captain": false,
                "role": "Bowler",
                "keeper": false,
                "substitute": false,
                "teamId": 62,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm fast medium",
                "teamName": "MI",
                "faceImageId": 226392
            },
            {
                "id": 8117,
                "name": "Boult",
                "fullName": "Trent Boult",
                "nickName": "Boult",
                "captain": false,
                "role": "Bowler",
                "keeper": false,
                "substitute": false,
                "teamId": 62,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Left Arm fast medium",
                "teamName": "MI",
                "faceImageId": 351612,
                "isOverseas": true
            },
            {
                "id": 1431171,
                "name": "Satyanarayana Raju",
                "fullName": "Satyanarayana Raju",
                "nickName": "Satyanarayana Raju",
                "captain": false,
                "role": "Batting Allrounder",
                "keeper": false,
                "substitute": false,
                "teamId": 62,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm fast medium",
                "teamName": "MI",
                "faceImageId": 182026
            }
        ],
        "bench": [
            {
                "id": 1447337,
                "name": "Vignesh Puthur",
                "fullName": "Vignesh Puthur",
                "nickName": "Vignesh Puthur",
                "captain": false,
                "role": "Batting Allrounder",
                "keeper": false,
                "substitute": true,
                "teamId": 62,
                "battingStyle": "RIGHT",
                "bowlingStyle": "",
                "teamName": "MI",
                "faceImageId": 182026,
                "inMatchChange": "MIN",
                "splSubstitute": true
            },
            {
                "id": 11684,
                "name": "Ashwani Kumar",
                "fullName": "Ashwani Kumar",
                "nickName": "Ashwani Kumar",
                "captain": false,
                "role": "Bowler",
                "keeper": false,
                "substitute": true,
                "teamId": 62,
                "battingStyle": "LEFT",
                "bowlingStyle": "Left Arm fast medium",
                "teamName": "MI",
                "faceImageId": 182026,
                "splSubstitute": true
            },
            {
                "id": 22601,
                "name": "Raj Bawa",
                "fullName": "Raj Bawa",
                "nickName": "Raj Bawa",
                "captain": false,
                "role": "Batting Allrounder",
                "keeper": false,
                "substitute": true,
                "teamId": 62,
                "battingStyle": "LEFT",
                "bowlingStyle": "Right Arm fast medium",
                "teamName": "MI",
                "faceImageId": 226295,
                "splSubstitute": true
            },
            {
                "id": 9576,
                "name": "Corbin Bosch",
                "fullName": "Corbin Bosch",
                "nickName": "Corbin Bosch",
                "captain": false,
                "role": "Bowling Allrounder",
                "keeper": false,
                "substitute": true,
                "teamId": 62,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm fast medium",
                "teamName": "MI",
                "faceImageId": 619864,
                "splSubstitute": true,
                "isOverseas": true
            },
            {
                "id": 1844,
                "name": "Karn Sharma",
                "fullName": "Karn Sharma",
                "nickName": "Karn Sharma",
                "captain": false,
                "role": "Bowler",
                "keeper": false,
                "substitute": true,
                "teamId": 62,
                "battingStyle": "LEFT",
                "bowlingStyle": "Right Arm leg break",
                "teamName": "MI",
                "faceImageId": 226391,
                "splSubstitute": true
            },
            {
                "id": 9311,
                "name": "Bumrah",
                "fullName": "Jasprit Bumrah",
                "nickName": "Bumrah",
                "captain": false,
                "role": "Bowler",
                "keeper": false,
                "substitute": true,
                "teamId": 62,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm fast",
                "teamName": "MI",
                "faceImageId": 591949
            },
            {
                "id": 8349,
                "name": "R Topley",
                "fullName": "Reece Topley",
                "nickName": "Topley",
                "captain": false,
                "role": "Bowler",
                "keeper": false,
                "substitute": true,
                "teamId": 62,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Left Arm fast medium",
                "teamName": "MI",
                "faceImageId": 627475,
                "isOverseas": true
            },
            {
                "id": 12071,
                "name": "Mujeeb",
                "fullName": "Mujeeb Ur Rahman",
                "nickName": "Mujeeb",
                "captain": false,
                "role": "Bowler",
                "keeper": false,
                "substitute": true,
                "teamId": 62,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm off break",
                "teamName": "MI",
                "faceImageId": 352446,
                "isOverseas": true
            },
            {
                "id": 9647,
                "name": "Hardik Pandya",
                "fullName": "Hardik Pandya",
                "nickName": "Hardik Pandya",
                "captain": false,
                "role": "Batting Allrounder",
                "keeper": false,
                "substitute": true,
                "teamId": 62,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm fast medium",
                "teamName": "MI",
                "faceImageId": 616519
            },
            {
                "id": 13082,
                "name": "Krishnan Shrijith",
                "fullName": "Krishnan Shrijith",
                "nickName": "KL Shrijith",
                "captain": false,
                "role": "WK-Batsman",
                "keeper": false,
                "substitute": true,
                "teamId": 62,
                "battingStyle": "LEFT",
                "bowlingStyle": "",
                "teamName": "MI",
                "faceImageId": 182026
            },
            {
                "id": 13747,
                "name": "Arjun Tendulkar",
                "fullName": "Arjun Tendulkar",
                "nickName": "Arjun Tendulkar",
                "captain": false,
                "role": "Bowling Allrounder",
                "keeper": false,
                "substitute": true,
                "teamId": 62,
                "battingStyle": "LEFT",
                "bowlingStyle": "Left Arm fast medium",
                "teamName": "MI",
                "faceImageId": 154048
            },
            {
                "id": 52428,
                "name": "Bevon Jacobs",
                "fullName": "Bevon Jacobs",
                "nickName": "Bevon Jacobs",
                "captain": false,
                "role": "Batting Allrounder",
                "keeper": false,
                "substitute": true,
                "teamId": 62,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm fast medium",
                "teamName": "MI",
                "faceImageId": 182026,
                "isOverseas": true
            },
            {
                "id": 657,
                "name": "Kieron Pollard",
                "fullName": "Kieron Pollard",
                "nickName": "Pollard",
                "role": "Batting coach",
                "teamId": 62,
                "teamName": "MI",
                "faceImageId": 226283,
                "isSupportStaff": true
            },
            {
                "id": 25,
                "name": "Sachin Tendulkar",
                "fullName": "Sachin Tendulkar",
                "nickName": "Tendulkar",
                "role": "ICON",
                "teamId": 62,
                "teamName": "MI",
                "faceImageId": 171004,
                "isSupportStaff": true
            },
            {
                "id": 111,
                "name": "Lasith Malinga",
                "fullName": "Lasith Malinga",
                "nickName": "Malinga",
                "role": "Bowling Coach",
                "teamId": 62,
                "teamName": "MI",
                "faceImageId": 170724,
                "isSupportStaff": true
            },
            {
                "id": 1805,
                "name": "Jagadeesh Arunkumar",
                "fullName": "Jagadeesh Arunkumar",
                "nickName": "Arunkumar",
                "role": "Assistant Batting Coach",
                "teamId": 62,
                "teamName": "MI",
                "faceImageId": 182026,
                "isSupportStaff": true
            },
            {
                "id": 101,
                "name": "Mahela Jayawardene",
                "fullName": "Mahela Jayawardene",
                "nickName": "Mahela",
                "role": "Head coach",
                "teamId": 62,
                "teamName": "MI",
                "faceImageId": 153241,
                "isSupportStaff": true
            },
            {
                "id": 50341,
                "name": "Carl Hopkinson",
                "fullName": "Carl Hopkinson",
                "nickName": "Carl Hopkinson",
                "role": "Fielding coach",
                "teamId": 62,
                "teamName": "MI",
                "faceImageId": 182026,
                "isSupportStaff": true
            }
        ]
    }
}