export let team1d = {
    "players": {
        "playing XI": [
            {
                "id": 11813,
                "name": "Ruturaj Gaikwad",
                "fullName": "Ruturaj Gaikwad",
                "nickName": "Gaikwad",
                "captain": true,
                "role": "Batsman",
                "keeper": false,
                "substitute": false,
                "teamId": 58,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm off break",
                "teamName": "CSK",
                "faceImageId": 333874
            },
            {
                "id": 11177,
                "name": "Rachin Ravindra",
                "fullName": "Rachin Ravindra",
                "nickName": "Ravindra",
                "captain": false,
                "role": "Batting Allrounder",
                "keeper": false,
                "substitute": false,
                "teamId": 58,
                "battingStyle": "LEFT",
                "bowlingStyle": "Left arm orthodox",
                "teamName": "CSK",
                "faceImageId": 351609,
                "isOverseas": true
            },
            {
                "id": 9427,
                "name": "Deepak Hooda",
                "fullName": "Deepak Hooda",
                "nickName": "Hooda",
                "captain": false,
                "role": "Batting Allrounder",
                "keeper": false,
                "substitute": false,
                "teamId": 58,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm off break",
                "teamName": "CSK",
                "faceImageId": 244970
            },
            {
                "id": 11195,
                "name": "Shivam Dube",
                "fullName": "Shivam Dube",
                "nickName": "Shivam Dube",
                "captain": false,
                "role": "Batting Allrounder",
                "keeper": false,
                "substitute": false,
                "teamId": 58,
                "battingStyle": "LEFT",
                "bowlingStyle": "Right Arm medium",
                "teamName": "CSK",
                "faceImageId": 593805
            },
            {
                "id": 587,
                "name": "Ravindra Jadeja",
                "fullName": "Ravindra Jadeja",
                "nickName": "Jadeja",
                "captain": false,
                "role": "Bowling Allrounder",
                "keeper": false,
                "substitute": false,
                "teamId": 58,
                "battingStyle": "LEFT",
                "bowlingStyle": "Left arm orthodox",
                "teamName": "CSK",
                "faceImageId": 616520
            },
            {
                "id": 10420,
                "name": "Sam Curran",
                "fullName": "Sam Curran",
                "nickName": "Sam Curran",
                "captain": false,
                "role": "Bowling Allrounder",
                "keeper": false,
                "substitute": false,
                "teamId": 58,
                "battingStyle": "LEFT",
                "bowlingStyle": "Left Arm fast medium",
                "teamName": "CSK",
                "faceImageId": 351581,
                "isOverseas": true
            },
            {
                "id": 265,
                "name": "Dhoni",
                "fullName": "MS Dhoni",
                "nickName": "Dhoni",
                "captain": false,
                "role": "WK-Batsman",
                "keeper": true,
                "substitute": false,
                "teamId": 58,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm medium",
                "teamName": "CSK",
                "faceImageId": 170677
            },
            {
                "id": 1593,
                "name": "Ashwin",
                "fullName": "Ravichandran Ashwin",
                "nickName": "Ashwin",
                "captain": false,
                "role": "Bowling Allrounder",
                "keeper": false,
                "substitute": false,
                "teamId": 58,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm off break",
                "teamName": "CSK",
                "faceImageId": 591961
            },
            {
                "id": 15452,
                "name": "Noor Ahmad",
                "fullName": "Noor Ahmad",
                "nickName": "Noor Ahmad",
                "captain": false,
                "role": "Bowler",
                "keeper": false,
                "substitute": false,
                "teamId": 58,
                "battingStyle": "RIGHT",
                "bowlingStyle": "",
                "teamName": "CSK",
                "faceImageId": 616569,
                "isOverseas": true
            },
            {
                "id": 15480,
                "name": "Nathan Ellis",
                "fullName": "Nathan Ellis",
                "nickName": "Nathan Ellis",
                "captain": false,
                "role": "Bowler",
                "keeper": false,
                "substitute": false,
                "teamId": 58,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm fast medium",
                "teamName": "CSK",
                "faceImageId": 619885,
                "isOverseas": true
            },
            {
                "id": 10952,
                "name": "Khaleel Ahmed",
                "fullName": "Khaleel Ahmed",
                "nickName": "Khaleel Ahmed",
                "captain": false,
                "role": "Bowler",
                "keeper": false,
                "substitute": false,
                "teamId": 58,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Left Arm fast medium",
                "teamName": "CSK",
                "faceImageId": 171017,
                "inMatchChange": "MOUT"
            }
        ],
        "bench": [
            {
                "id": 9012,
                "name": "Tripathi",
                "fullName": "Rahul Tripathi",
                "nickName": "Tripathi",
                "captain": false,
                "role": "Batsman",
                "keeper": false,
                "substitute": true,
                "teamId": 58,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm medium",
                "teamName": "CSK",
                "faceImageId": 594322,
                "inMatchChange": "MIN",
                "splSubstitute": true
            },
            {
                "id": 12092,
                "name": "K Nagarkoti",
                "fullName": "Kamlesh Nagarkoti",
                "nickName": "K Nagarkoti",
                "captain": false,
                "role": "Bowler",
                "keeper": false,
                "substitute": true,
                "teamId": 58,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm fast",
                "teamName": "CSK",
                "faceImageId": 226313,
                "splSubstitute": true
            },
            {
                "id": 8204,
                "name": "Vijay Shankar",
                "fullName": "Vijay Shankar",
                "nickName": "Shankar",
                "captain": false,
                "role": "Batting Allrounder",
                "keeper": false,
                "substitute": true,
                "teamId": 58,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm medium",
                "teamName": "CSK",
                "faceImageId": 170664,
                "splSubstitute": true
            },
            {
                "id": 8512,
                "name": "Jamie Overton",
                "fullName": "Jamie Overton",
                "nickName": "Jamie Overton",
                "captain": false,
                "role": "Bowler",
                "keeper": false,
                "substitute": true,
                "teamId": 58,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm fast",
                "teamName": "CSK",
                "faceImageId": 617410,
                "splSubstitute": true,
                "isOverseas": true
            },
            {
                "id": 22571,
                "name": "Shaik Rasheed",
                "fullName": "Shaik Rasheed",
                "nickName": "Shaik Rasheed",
                "captain": false,
                "role": "Batsman",
                "keeper": false,
                "substitute": true,
                "teamId": 58,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm leg break",
                "teamName": "CSK",
                "faceImageId": 594287,
                "splSubstitute": true
            },
            {
                "id": 9838,
                "name": "Conway",
                "fullName": "Devon Conway",
                "nickName": "Conway",
                "captain": false,
                "role": "WK-Batsman",
                "keeper": false,
                "substitute": true,
                "teamId": 58,
                "battingStyle": "LEFT",
                "bowlingStyle": "Right Arm medium",
                "teamName": "CSK",
                "faceImageId": 616434,
                "isOverseas": true
            },
            {
                "id": 16458,
                "name": "Matheesha Pathirana",
                "fullName": "Matheesha Pathirana",
                "nickName": "Pathirana",
                "captain": false,
                "role": "Bowler",
                "keeper": false,
                "substitute": true,
                "teamId": 58,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm fast",
                "teamName": "CSK",
                "faceImageId": 351888,
                "isOverseas": true
            },
            {
                "id": 13184,
                "name": "Mukesh Choudhary",
                "fullName": "Mukesh Choudhary",
                "nickName": "Mukesh Choudhary",
                "captain": false,
                "role": "Bowler",
                "keeper": false,
                "substitute": true,
                "teamId": 58,
                "battingStyle": "LEFT",
                "bowlingStyle": "Left Arm fast medium",
                "teamName": "CSK",
                "faceImageId": 182026
            },
            {
                "id": 14598,
                "name": "Anshul Kamboj",
                "fullName": "Anshul Kamboj",
                "nickName": "Anshul Kamboj",
                "captain": false,
                "role": "Bowling Allrounder",
                "keeper": false,
                "substitute": true,
                "teamId": 58,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm fast medium",
                "teamName": "CSK",
                "faceImageId": 182026
            },
            {
                "id": 9746,
                "name": "Shreyas Gopal",
                "fullName": "Shreyas Gopal",
                "nickName": "Shreyas Gopal",
                "captain": false,
                "role": "Bowler",
                "keeper": false,
                "substitute": true,
                "teamId": 58,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm leg break",
                "teamName": "CSK",
                "faceImageId": 226505
            },
            {
                "id": 19807,
                "name": "Gurjapneet Singh",
                "fullName": "Gurjapneet Singh",
                "nickName": "Gurjapneet Singh",
                "captain": false,
                "role": "Bowler",
                "keeper": false,
                "substitute": true,
                "teamId": 58,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Left Arm fast medium",
                "teamName": "CSK",
                "faceImageId": 182026
            },
            {
                "id": 32835,
                "name": "Ramakrishna Ghosh",
                "fullName": "Ramakrishna Ghosh",
                "nickName": "Ramakrishna Ghosh",
                "captain": false,
                "role": "Batting Allrounder",
                "keeper": false,
                "substitute": true,
                "teamId": 58,
                "battingStyle": "RIGHT",
                "bowlingStyle": "Right Arm fast medium",
                "teamName": "CSK",
                "faceImageId": 182026
            },
            {
                "id": 1427488,
                "name": "Andre Siddarth C",
                "fullName": "Andre Siddarth C",
                "nickName": "Andre Siddarth C",
                "captain": false,
                "role": "Batsman",
                "keeper": false,
                "substitute": true,
                "teamId": 58,
                "battingStyle": "RIGHT",
                "bowlingStyle": "",
                "teamName": "CSK",
                "faceImageId": 182026
            },
            {
                "id": 1429626,
                "name": "Vansh Bedi",
                "fullName": "Vansh Bedi",
                "nickName": "Vansh Bedi",
                "captain": false,
                "role": "WK-Batsman",
                "keeper": false,
                "substitute": true,
                "teamId": 58,
                "battingStyle": "LEFT",
                "bowlingStyle": "",
                "teamName": "CSK",
                "faceImageId": 182026
            },
            {
                "id": 49,
                "name": "Stephen Fleming",
                "fullName": "Stephen Fleming",
                "nickName": "Stephen Fleming",
                "role": "Head coach",
                "teamId": 58,
                "teamName": "CSK",
                "faceImageId": 151497,
                "isSupportStaff": true
            },
            {
                "id": 4772,
                "name": "Michael Hussey",
                "fullName": "Michael Hussey",
                "nickName": "M Hussey",
                "role": "Batting coach",
                "teamId": 58,
                "teamName": "CSK",
                "faceImageId": 180290,
                "isSupportStaff": true
            },
            {
                "id": 5487,
                "name": "Eric Simons",
                "fullName": "Eric Simons",
                "nickName": "Simons",
                "role": "Bowling Consultant",
                "teamId": 58,
                "teamName": "CSK",
                "faceImageId": 157813,
                "isSupportStaff": true
            },
            {
                "id": 42611,
                "name": "Rajiv Kumar",
                "fullName": "Rajiv Kumar",
                "nickName": "Rajiv Kumar",
                "role": "Fielding coach",
                "teamId": 58,
                "teamName": "CSK",
                "faceImageId": 182026,
                "isSupportStaff": true
            }
        ]
    }
}